name: docs-build
on:
    pull_request:
        branches:
            - main
           
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  pip install --no-cache-dir Cython
                  pip install -r requirements.txt -r requirements_dev.txt  -r requirements_docs.txt
                  pip install .
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
            - name: Build docs
              run: |
                  mkdocs build
           