# name: docs
# on:
#     push:
#         branches:
#             - main
#     pull_request:
#         branches:
#             - main
# jobs:
#     deploy:
#         runs-on: ubuntu-latest
#         permissions: 
#             contents: write
#         steps:
#             - uses: actions/checkout@v3
#             - uses: actions/setup-python@v4
#               with:
#                   python-version: "3.11"
#             - name: Install dependencies
#               run: |
#                   python -m pip install --upgrade pip
#                   pip install --user --no-cache-dir Cython
#                   pip install --user -r requirements.txt
#                   pip install --user -r requirements_dev.txt
#                   pip install .
#             - name: PKG-TEST
#               run: |
#                   python -m unittest discover tests/
#             - run: python -m pip install --upgrade pip
#             - run: pip install -r requirements_docs.txt
#             - run: mkdocs gh-deploy --force


name: docs
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions: 
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Install Poetry
              run: |
                  curl -sSL https://install.python-poetry.org | python3 -
                  echo "$HOME/.local/bin" >> $GITHUB_PATH
            - name: Install dependencies
              run: |
                  poetry install --sync --no-interaction --with docs
            - name: PKG-TEST
              run: |
                  poetry run python -m unittest discover tests/
            - name: Build and deploy docs
              run: poetry run mkdocs gh-deploy --force