on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Linux build
jobs:
    test-ubuntu:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.10" }
                    - { os: ubuntu-latest, py: "3.11" }
                    - { os: ubuntu-latest, py: "3.12" }
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.config.py }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install .[all]
            - name: PKG-TEST
              run: |
                  python -m unittest discover tests/
                  python -m pytest tests/
