on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Windows build

jobs:
    test-windows:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }} (${{ matrix.python-version}})
        strategy:
            fail-fast: false
            matrix:
              os: ["windows-latest"]
              python-version: ["3.11"]
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install miniconda
            uses: conda-incubator/setup-miniconda@v2
            with:
              auto-activate-base: true
              python-version: ${{ matrix.python-version}}
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install --user --no-cache-dir Cython
                pip install .[all]

